//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demkaTUT
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Table_2
    {
        public int id { get; set; }
        public string name { get; set; }
        public string decription { get; set; }
        public string vendor { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<int> discount { get; set; }
        public byte[] image { get; set; }
        public SolidColorBrush solidColorBrush
        {
            get
            {
                if (this.discount >= 15)
                {
                    SolidColorBrush brush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#7fff00"));
                    return brush;
                }
                else
                {
                    return Brushes.Transparent;
                }
            }
        }
        public string Img
        {
            get { return "/Resources/" + this.name + ".jpg"; }
        }
        public string NameText
        {
            get
            {
                return "Наименование:\n" + this.name;
            }
        }
        public string DescriptionText
        {
            get
            {
                return "Описание:\n" + this.decription;
            }
        }
        public string VendorText
        {
            get
            {
                return "Производитель:\n" + this.vendor;
            }
        }
        public string PriceText
        {
            get
            {
                if (this.discount > 0)
                {
                    string str = this.price.ToString();
                    float? newPrice = this.price - (this.price * this.discount / 100);
                    string through = "";
                    foreach (char c in str)
                    {
                        through += c + "\u0336";
                    }
                    return "Старая цена:\n" + through + "\nЦена:\n" + newPrice + "р.";
                }
                else
                {
                    return "Цена:\n" + this.price + "р.";
                }
            }
        }
        public string DiscountText
        {
            get
            {
                return "Скидка:\n" + this.discount + "%";
            }
        }
    }
}
